services:
  gateway:
    build: .
    image: hermes-agent
    container_name: hermes
    restart: unless-stopped
    network_mode: host
    volumes:
      - ~/.hermes:/opt/data
    environment:
      - HERMES_UID=${HERMES_UID:-10000}
      - HERMES_GID=${HERMES_GID:-10000}
    command:
      - gateway
      - run
  dashboard:
    image: hermes-agent
    container_name: hermes-dashboard
    restart: unless-stopped
    depends_on:
      - gateway
    networks:
      - dokploy-network
    volumes:
      - ~/.hermes:/opt/data
    environment:
      - HERMES_UID=${HERMES_UID:-10000}
      - HERMES_GID=${HERMES_GID:-10000}
    command:
      - dashboard
      - --host
      - 0.0.0.0
      - --no-open
      - --insecure
    labels:
      - traefik.enable=true
      - traefik.docker.network=dokploy-network
      - traefik.http.routers.hermes-web.entrypoints=web
      - traefik.http.routers.hermes-web.rule=Host(`hermes.srv1748663.hstgr.cloud`)
      - traefik.http.routers.hermes-web.middlewares=redirect-to-https@file
      - traefik.http.routers.hermes-web.service=hermes
      - traefik.http.routers.hermes-websecure.entrypoints=websecure
      - traefik.http.routers.hermes-websecure.rule=Host(`hermes.srv1748663.hstgr.cloud`)
      - traefik.http.routers.hermes-websecure.tls.certresolver=letsencrypt
      - traefik.http.routers.hermes-websecure.service=hermes
      - traefik.http.routers.hermes-websecure.middlewares=hermes-auth
      - traefik.http.services.hermes.loadbalancer.server.port=9119
      - traefik.http.middlewares.hermes-auth.basicauth.users=hermes:$$apr1$$xe2M9i6y$$z2sikwE3704Qm7zM5AwZD0
